server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/configuration-snippet: |-
        proxy_ssl_server_name on;
        proxy_ssl_name $host;
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/secure-backends: "true"
    hosts:
      - argocd.potsdam-softwareentwicklung.de
    tls:
      - hosts:
          - argocd.potsdam-softwareentwicklung.de
        secretName: argocd-tls-secret
    https: true

  config:
    url: https://argocd.potsdam-softwareentwicklung.de
